export { General } from "./General"
export { Home } from "./Home"
export { Login } from "./Login"
export { MovieDetail } from "./MovieDetail"
export { NotFound } from "./NotFound"
export { Trendings } from "./Trendings"
